// Code generated by protoc-gen-go-grpcproxy. DO NOT EDIT.

package add

import (
	gin "github.com/gin-gonic/gin"
	grpcproxy "github.com/go-leo/grpcproxy"
	grpc "google.golang.org/grpc"
	metadata "google.golang.org/grpc/metadata"
	http "net/http"
)

func AddProxyRoutes(cli AddClient) []grpcproxy.Route {
	return []grpcproxy.Route{
		grpcproxy.NewRoute(
			http.MethodPost,
			"/add.Add/Sum",
			func(c *gin.Context) {
				req := new(SumRequest)
				if err := grpcproxy.Bind(c, req); err != nil {
					c.String(http.StatusBadRequest, err.Error())
					_ = c.Error(err).SetType(gin.ErrorTypeBind)
					return
				}
				ctx := grpcproxy.NewContext(c)
				var headerMD, trailerMD metadata.MD
				resp, err := cli.SayHello(ctx, req, grpc.Header(&headerMD), grpc.Trailer(&trailerMD))
				grpcproxy.Render(c, headerMD, trailerMD, resp, err)
			},
		),
		grpcproxy.NewRoute(
			http.MethodPost,
			"/add.Add/Concat",
			func(c *gin.Context) {
				req := new(ConcatRequest)
				if err := grpcproxy.Bind(c, req); err != nil {
					c.String(http.StatusBadRequest, err.Error())
					_ = c.Error(err).SetType(gin.ErrorTypeBind)
					return
				}
				ctx := grpcproxy.NewContext(c)
				var headerMD, trailerMD metadata.MD
				resp, err := cli.SayHello(ctx, req, grpc.Header(&headerMD), grpc.Trailer(&trailerMD))
				grpcproxy.Render(c, headerMD, trailerMD, resp, err)
			},
		),
	}
}
