// Code generated by "gors -service AccountServer"; DO NOT EDIT.

package account

import (
	gin "github.com/gin-gonic/gin"
	binding "github.com/gin-gonic/gin/binding"
	gors "github.com/go-leo/gors"
	http "net/http"
)

func AccountServerRoutes(srv AccountServer) []gors.Route {
	return []gors.Route{
		gors.NewRoute(
			http.MethodPost,
			"/account/register",
			func(c *gin.Context) {
				var req *User
				var resp *Empty
				var err error
				req = new(User)
				if err = c.ShouldBindWith(req, binding.JSON); err != nil {
					c.String(http.StatusBadRequest, err.Error())
					_ = c.Error(err).SetType(gin.ErrorTypeBind)
					return
				}
				if err = gors.Validate(req); err != nil {
					c.String(http.StatusBadRequest, err.Error())
					_ = c.Error(err).SetType(gin.ErrorTypeBind)
					return
				}
				ctx := gors.NewContext(c)
				resp, err = srv.Register(ctx, req)
				if gors.IsInterrupted(ctx) {
					return
				}
				if err != nil {
					if httpErr, ok := err.(*gors.HttpError); ok {
						c.String(httpErr.StatusCode(), httpErr.Error())
						_ = c.Error(err).SetType(gin.ErrorTypePublic)
						return
					}
					c.String(http.StatusInternalServerError, err.Error())
					_ = c.Error(err).SetType(gin.ErrorTypePrivate)
					return
				}
				statusCode := gors.GetCodeFromContext(ctx)
				c.JSON(statusCode, resp)
			},
		),
		gors.NewRoute(
			http.MethodPost,
			"/account/login",
			func(c *gin.Context) {
				var req *User
				var resp *Empty
				var err error
				req = new(User)
				if err = c.ShouldBindWith(req, binding.JSON); err != nil {
					c.String(http.StatusBadRequest, err.Error())
					_ = c.Error(err).SetType(gin.ErrorTypeBind)
					return
				}
				if err = gors.Validate(req); err != nil {
					c.String(http.StatusBadRequest, err.Error())
					_ = c.Error(err).SetType(gin.ErrorTypeBind)
					return
				}
				ctx := gors.NewContext(c)
				resp, err = srv.Login(ctx, req)
				if gors.IsInterrupted(ctx) {
					return
				}
				if err != nil {
					if httpErr, ok := err.(*gors.HttpError); ok {
						c.String(httpErr.StatusCode(), httpErr.Error())
						_ = c.Error(err).SetType(gin.ErrorTypePublic)
						return
					}
					c.String(http.StatusInternalServerError, err.Error())
					_ = c.Error(err).SetType(gin.ErrorTypePrivate)
					return
				}
				statusCode := gors.GetCodeFromContext(ctx)
				c.JSON(statusCode, resp)
			},
		),
	}
}
